on:
  push:
    branches:
      main

name: Terraform Destroy with tf-destroy.yml file

jobs:
  terraform:
    name: 'Terraform-Destroy'
    runs-on: [self-hosted, Windows, x64, LTIM_VM]
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VERSION: 1.8.5

    defaults:
      run:
        shell: cmd
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

     # - name: Terraform fmt
     #   id: fmt
     #   run: terraform fmt -check

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve
