on:
  workflow_dispatch:
  push:
    branches:
      none
permissions:
  id-token: write
  contents: read
  pull-requests: write
  
name: Replace token test

jobs:
  ReplaceToken:
    name: 'ReplaceToken'
    runs-on: ubuntu-latest
    # runs-on: [self-hosted]
    env:
      #ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_ID: "12345"
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VERSION: 1.8.5
      tfstatefile: dev.terraform.tfstate

    defaults:
      run:
        shell: bash
        working-directory: .
       
    steps:
      - name: Checkout
        uses: actions/checkout@v2   
        
      - name: txt
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '{'
          tokenSuffix: '}'
          files: '["hemant.txt"]'
      - name: Display hemant.txt
        run: cat hemant.txt
        
      - name: conf
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '{'
          tokenSuffix: '}'
          files: '["hemant.conf"]'
          
      - name: Display hemant.conf
        run: cat hemant.conf
        
      - name: tf
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '__'
          tokenSuffix: '__'
          files: '["backend.tf"]'      
          
      - name: Display backend.tf
        run: cat backend.tf    
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}    
          
      - name: Terraform init
        id: init
        run: |
          terraform init        
